### ISSUE TITLE
A warm pool for the asg would reduce spin up times

### ISSUE THREAD

**Issue by nitrocode** [chime/terraform-aws-alternat#103]
In the readme, it speaks of the high spin up time for ipv6. A warm pool should help with that

https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-warm-pools.html

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#warm_pool

**Comment by bwhaley** [comment]
A warm pool would keep an extra NAT instance running all the time. I think the bootstrap script would need a fair bit of refactoring to support such a configuration. Right now, a new NAT instance boots, configures itself as a NAT, finds and associates and EIP, and then claims the default route. A standby instance would have to boot, configure itself as a NAT, then basically hibernate until it's time to claim the EIP and route. This is possible, but I'm not sure there's much benefit. Regarding the IPv6 slow boot issue, the workaround of preferring IPv4 seems fine to me. There's probably a better fix for whatever the root cause of the slowness is.

Thanks for suggesting it, as I always like to hear about possible improvements. In this case though, unless somebody wants to make a strong case for it, I don't think we'll implement this.

**Comment by nitrocode** [comment]
Thank you for considering
