### ISSUE TITLE
Any plan to extend this to other major clouds?

### ISSUE THREAD

**Issue by beyondbill** [chime/terraform-aws-alternat#105]
I'm really impressed after reading the README and watching the [demo](https://www.youtube.com/watch?v=KtODOJPSz8A&t=1960s). Wonder if the maintainers have any plan to extend the same idea to other major clouds, such as Azure and GCP. Obviously each cloud needs a different implementation of Terraform code due to different cloud APIs. However, it seems to me that all the basic components used in this repo are already ready in GCP and Azure. I could be wrong though. Would like to know if there's any known blocker in clouds other than AWS. Thanks!

**Comment by bwhaley** [comment]
Hi, thanks for your interest. We have no plans to implement anything for GCP or Azure. Not sure if they have the same problem with NAT as AWS does or if it could be solved in the same way, but my hunch is that a direct port of Alternat is probably not possible.

Anyone who has more experience with these platforms is welcome to weigh in, but I'm going to close this one since we don't have any plans to do this.
