### ISSUE TITLE
Upstream terraform module to upstream registry

### ISSUE THREAD

**Issue by nitrocode** [chime/terraform-aws-alternat#84]
Please consider adding the terraform module to the upstream registry

https://registry.terraform.io/search/modules?q=Alternat

https://github.com/opentofu/registry/?tab=readme-ov-file

In order to submit the module, it may be needed to move the terraform code to a separate repo such as `1debit/terraform-aws-alternat` with a readme generated from [`terraform-docs`](https://github.com/terraform-docs/terraform-docs)

Once submitted and accepted, the module will be findable using the registry search allowing more users to access the product.

Thank you.

**Comment by nitrocode** [comment]
Oh I just saw this in the readme

> Why isn't this module published on the Terraform registry?

While we'd like for this to be available on the Terraform Registry, it requires a specific repo naming convention and folder structure that we do not want to adopt.

May I ask why? I couldn't find another mention in the issues

**Comment by bwhaley** [comment]
The reason was that I had originally planned to use this repository for multiple versions of alterNAT, e.g. CDK, Pulumi, etc. But I ended up releasing the CDK implementation at https://github.com/cdk-community/alternat and I haven't heard any interest in a Pulumi implementation, and even if there was, it would probably live in its own repository.

I think we could add this to the Terraform module registry. That would be a breaking change, but still possible. I'm planning another breaking change soon as well (make Python runtime the default rather than Docker), so maybe they can be combined in a single release.

**Comment by nitrocode** [comment]
Awesome. Thank you!
